WebApplication/MoviesCatalog/Models/Director.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Movies.Models
{
    public class Director
    {
        public Director()
        {
            this.Movies = new HashSet<Movie>();
        }
        public int Id { get; set; }
        [Required]
        [Display(Name = "Име")]
        public string FirstName { get; set; }
        [Required]
        [Display(Name = "Фамилия")]
        public string LastName { get; set; }
        [Column(TypeName = "date")]
        [Display(Name = "Дата на раждане")]
        public DateTime? Born { get; set; }
        [Display(Name = "Страна")]
        public string HomeTown { get; set; }
        public virtual ICollection<Movie> Movies { get; set; }
      
    }
}

WebApplication/MoviesCatalog/Controllers/DirectorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Movies.Models;

namespace Movies.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DirectorController : Controller
    {
        // GET: Director
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        // GET: Director/List
        public ActionResult List()
        {
            using (var database = new MoviesDbContext())
            {
                var directors = database.Directors
                    .ToList();
                return View(directors);
            }
        }


        // GET: Director/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Director/Create
        [HttpPost]
        public ActionResult Create(Director director)
        {
            if (ModelState.IsValid)
            {
                using (var database = new MoviesDbContext())
                {
                    database.Directors.Add(director);
                    database.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
            TempData["Success"] = "Режисьорът е създаден успешно.";
            return View(director);
        }

        // GET: Director/edit
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var database = new MoviesDbContext())
            {
                var director = database.Directors
                    .FirstOrDefault(d => d.Id == id);

                if (director == null)
                {
                    return HttpNotFound();
                }

                return View(director);
            }
        }

        // GET: Director/Edit
        [HttpPost]
        public ActionResult Edit(Director director)
        {
            if (ModelState.IsValid)
            {
                using (var database = new MoviesDbContext())
                {
                    database.Entry(director).State = System.Data.Entity.EntityState.Modified;
                    database.SaveChanges();
                    TempData["Success"] = "Режисьорът е редактиран успешно.";
                    return RedirectToAction("Index");
                }
            }
            TempData["Danger"] = "Некоректни данни. Моля, опитайте отново.";
            return View(director);
        }

        // GET: Director/Delete
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var database = new MoviesDbContext())
            {
                var director = database.Directors
                    .FirstOrDefault(d => d.Id == id);

                if (director == null)
                {
                    return HttpNotFound();
                }

                return View(director);
            }
        }

        // POST: Director/Delete
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int? id)
        {
            using (var database = new MoviesDbContext())
            {
                var director = database.Directors
                    .FirstOrDefault(d => d.Id == id);

                var movies = database.Movies.Where(m => m.DirectorId == director.Id).ToList();
                foreach (var movie in movies)
                {

                    string fullPathPrimary = Request.MapPath("~/Content/UploadedImages/" + movie.Image);
                    if (System.IO.File.Exists(fullPathPrimary))
                    {
                        System.IO.File.Delete(fullPathPrimary);
                    }
                    database.Movies.Remove(movie);
                }


                database.Directors.Remove(director);
                database.SaveChanges();
                TempData["Success"] = "Премахнат успешно.";
                return RedirectToAction("Index");

            }


        }
    }
}

WebApplication/MoviesCatalog/Views/Director/Create.cshtml
@model Movies.Models.Director

@{
    ViewBag.Title = "Добавяне на режисьор";
}

<div class="container">
    <div class="well">
        <h2>Добави режисьор</h2>
        @using (@Html.BeginForm("Create", "Director", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <div class="form-group span=8 offset=2">
                @Html.LabelFor(m => m.FirstName, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group span=8 offset=2">
                @Html.LabelFor(m => m.LastName, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group span=8 offset=2">
                @Html.LabelFor(m => m.Born, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Born, new { @type = "date", @class = "form-control" })
                </div>
            </div>


            <div class="form-group span=8 offset=2">
                @Html.LabelFor(m => m.HomeTown, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.HomeTown, new { @class = "form-control" })
                </div>
            </div>



            <div class="form-group">
                <div class="col-sm-offset-4 col-sm-4">
                    @Html.ActionLink("Назад", "Index", "Director", new { @class = "btn btn-default" })
                    <input type="submit" value="Добави" class="btn btn-success" />
                </div>
            </div>
        }
    </div>
</div>

WebApplication/MoviesCatalog/Views/Director/Delete.cshtml
@model Movies.Models.Director
@{
    ViewBag.Title = "Изтриване на режисьор";
}

<div class="container">
    <div class="well">
        <h2>Изтрий режисьор</h2>
        @using (Html.BeginForm("Delete", "Director", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <div class="form-group">
                @Html.LabelFor(m => m.FirstName, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4 ">
                    @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.LastName, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4 ">
                    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>

            


            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    @Html.ActionLink("Назад", "List", "Director", new { @class = "btn btn-default" })
                    <input type="submit" value="Изтрий" class="btn btn-danger" />
                </div>
            </div>
        }
    </div>
</div>

WebApplication/MoviesCatalog/Views/Director/Edit.cshtml
@model Movies.Models.Director
@{
    ViewBag.Title = "Редактиране на режисьор";
}

<div class="container">
    <div class="well">
        <h2>Редактирай режисьор</h2>
        @using (Html.BeginForm("Edit", "Director", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <div class="form-group">
                @Html.LabelFor(m => m.FirstName, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.LastName, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Born, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    
                    @Html.TextBoxFor(m => m.Born, "{0:yyyy-MM-dd}", new { type="date", @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.HomeTown, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.HomeTown, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    @Html.ActionLink("Назад", "List", "Director", new { @class = "btn btn-default" })
                    <input type="submit" value="Редактирай" class="btn btn-success" />
                </div>
            </div>
        }
    </div>
</div>

WebApplication/MoviesCatalog/Views/Director/List.cshtml
@model List<Movies.Models.Director>

@{
    ViewBag.Title = "Всички режисьори";
}

<div class="container">
    <div class="well">
        <h2>Всички режисьори - @Html.ActionLink("Добави", "Create", "Director", null, new { @class = "btn btn-warning" })</h2>
        <div class="row">
            <table class="table table-striped table-hover col-sm-12">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Име</th>
                    <th>Фамилия</th>
                    <th>Дата на раждане</th>
                    <th>Страна</th>
                    <th>Опции</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var director in Model)
                {
                    <tr>
                        <td>@director.Id</td>
                        <td>@director.FirstName</td>
                        <td>@director.LastName</td>
                        @{
                            string date;
                            if (@director.Born == null)
                            {

                                date = "-";
                            }
                            else
                            {
                                date = @director.Born.Value.ToString("dd MMMM yyyy");
                            }
                        }
                        <td>@date</td>
                        <td>@director.HomeTown</td>
                        <td>
                            @Html.ActionLink("Редактирай", "Edit", "Director", new { @id = director.Id }, null)
                            @Html.ActionLink("Изтрий", "Delete", "Director", new { @id = director.Id }, null)
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>